[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "Gwo9U4kAXviBuui7VsrdLWJ7y8daf5JZc4BBtHTFh7TP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/maxwu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
